pal_swap_init_system(0)
global.boxlist = ds_list_create()
ds_list_add(global.boxlist, "box1")
ds_list_add(global.boxlist, "box2")
ds_list_add(global.boxlist, "box3")
ds_list_add(global.boxlist, "box4")
ds_list_add(global.boxlist, "box5")
